2023-11-07 14:49:03.924 [main] ERROR o.s.b.diagnostics.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

2023-11-07 14:49:54.175 [http-nio-8085-exec-2] ERROR o.a.c.c.C.[.[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.translateException(LettuceConnectionFactory.java:1534)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1442)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1228)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1211)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedConnection(LettuceConnectionFactory.java:975)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:360)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:134)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:97)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:84)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:215)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
	at org.springframework.data.redis.core.DefaultValueOperations.set(DefaultValueOperations.java:236)
	at com.gec.system.filter.TokenLoginFilter.successfulAuthentication(TokenLoginFilter.java:100)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:240)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at com.gec.system.filter.TokenAuthenticationFilter.doFilterInternal(TokenAuthenticationFilter.java:45)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to 127.0.0.1:6379
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:242)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:206)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:115)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:115)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1440)
	... 65 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2023-11-07 14:52:58.524 [main] ERROR o.s.b.diagnostics.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

2023-11-07 14:55:04.831 [http-nio-8085-exec-6] ERROR com.gec.system.exception.GlobalException - 未知异常
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xiaoli' for key 'idx_username'
### The error may exist in com/gec/system/mapper/SysUserMapper.java (best guess)
### The error may involve com.gec.system.mapper.SysUserMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO sys_user  ( username, password, name, phone,      create_time, update_time )  VALUES  ( ?, ?, ?, ?,      ?, ? )
### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xiaoli' for key 'idx_username'
; Duplicate entry 'xiaoli' for key 'idx_username'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xiaoli' for key 'idx_username'
2023-11-07 14:55:56.944 [main] ERROR o.s.b.diagnostics.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

2023-11-07 14:56:20.680 [http-nio-8085-exec-1] ERROR com.gec.system.exception.GlobalException - 未知异常
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
### The error may exist in com/gec/system/mapper/SysUserMapper.java (best guess)
### The error may involve com.gec.system.mapper.SysUserMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO sys_user  ( username, password, name, phone,      create_time, update_time )  VALUES  ( ?, ?, ?, ?,      ?, ? )
### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
; Duplicate entry 'xaioli' for key 'idx_username'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
2023-11-07 14:56:54.910 [http-nio-8085-exec-2] ERROR com.gec.system.exception.GlobalException - 未知异常
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
### The error may exist in com/gec/system/mapper/SysUserMapper.java (best guess)
### The error may involve com.gec.system.mapper.SysUserMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO sys_user  ( username, password, name, phone,      create_time, update_time )  VALUES  ( ?, ?, ?, ?,      ?, ? )
### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
; Duplicate entry 'xaioli' for key 'idx_username'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
2023-11-07 14:57:51.981 [http-nio-8085-exec-1] ERROR com.gec.system.exception.GlobalException - 未知异常
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
### The error may exist in com/gec/system/mapper/SysUserMapper.java (best guess)
### The error may involve com.gec.system.mapper.SysUserMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO sys_user  ( username, password, name, phone,      create_time, update_time )  VALUES  ( ?, ?, ?, ?,      ?, ? )
### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
; Duplicate entry 'xaioli' for key 'idx_username'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
2023-11-07 14:58:13.226 [http-nio-8085-exec-4] ERROR com.gec.system.exception.GlobalException - 未知异常
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
### The error may exist in com/gec/system/mapper/SysUserMapper.java (best guess)
### The error may involve com.gec.system.mapper.SysUserMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO sys_user  ( username, password, name, phone,      create_time, update_time )  VALUES  ( ?, ?, ?, ?,      ?, ? )
### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
; Duplicate entry 'xaioli' for key 'idx_username'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
2023-11-07 14:59:30.535 [main] ERROR o.s.b.diagnostics.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

2023-11-07 14:59:49.529 [http-nio-8085-exec-1] ERROR com.gec.system.exception.GlobalException - 未知异常
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
### The error may exist in com/gec/system/mapper/SysUserMapper.java (best guess)
### The error may involve com.gec.system.mapper.SysUserMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO sys_user  ( username, password, name, phone,      create_time, update_time )  VALUES  ( ?, ?, ?, ?,      ?, ? )
### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
; Duplicate entry 'xaioli' for key 'idx_username'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xaioli' for key 'idx_username'
2023-11-07 15:00:41.768 [http-nio-8085-exec-7] ERROR com.gec.system.exception.GlobalException - 未知异常
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xiaoli' for key 'idx_username'
### The error may exist in com/gec/system/mapper/SysUserMapper.java (best guess)
### The error may involve com.gec.system.mapper.SysUserMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO sys_user  ( username, password, name, phone,      create_time, update_time )  VALUES  ( ?, ?, ?, ?,      ?, ? )
### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xiaoli' for key 'idx_username'
; Duplicate entry 'xiaoli' for key 'idx_username'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xiaoli' for key 'idx_username'
2023-11-07 15:01:38.196 [main] ERROR o.s.b.diagnostics.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

2023-11-07 15:02:05.242 [http-nio-8085-exec-3] ERROR com.gec.system.exception.GlobalException - 未知异常
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xiaoli' for key 'idx_username'
### The error may exist in com/gec/system/mapper/SysUserMapper.java (best guess)
### The error may involve com.gec.system.mapper.SysUserMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO sys_user  ( username, password, name, phone,      create_time, update_time )  VALUES  ( ?, ?, ?, ?,      ?, ? )
### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xiaoli' for key 'idx_username'
; Duplicate entry 'xiaoli' for key 'idx_username'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xiaoli' for key 'idx_username'
